version: '3.8'
services:
  weatherforecastapi:
    container_name: weatherforecastapi
    build:
      context: .
      dockerfile: ./WeatherForecast.Api/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure



